src/chi/components/divider/divider.scss, src/website/views/components/divider.pug
- Added divider support for `<hr>` tags. This required specifying a `border:none;`on `a-divider` to eliminate the default inset.
- Updated base divider color value from `0.2` to `0.12`
- Updated documentation copy
=> Updated divider documentation

src/chi/components/modal/modal.scss, src/chi/utilities/spacing.scss, src/website/views/components/modal.pug, src/website/views/utilities/spacing.pug
- Increased spacing utility values to support a max margin/padding of 80px versus the previous 48px.
- Eliminated modal close's dependence on modal header. Modals can now be created without headers and the close button will still render properly.
- Added new modal example
=> Added new modal example to documentation

src/chi/components/buttons/button-groups.scss, src/chi/components/card/card.scss, src/chi/components/grid/grid.scss, src/website/views/components/button-group.pug, src/website/views/components/card.pug, src/website/views/foundations/grid.pug, test/chi/components/button-horizontal-groups.pug, test/chi/components/button-vertical-groups.pug, test/chi/components/card.pug, test/chi/components/hybrid-buttons.pug, test/chi/foundations/grid.pug
Updated alignTop, alignBottom, and alignCenter from grid fundamentals. Also updated alignRight and alignLeft in buttons and cards.
```
([^_a-zA-Z0-9-])-align(Bottom|Top|Center|Left|Right)([^_a-zA-Z0-9-]) => $1-align--\L$2$3
([^_a-zA-Z0-9-])align(Bottom|Top|Center|Left|Right)([^_a-zA-Z0-9-]) => $1align--\L$2$3
```
=> [CHI-134] Update grid alignment notation

src/website/layouts/partials/header.pug
This is dependent on CHI-150 which needs to load chi core globally
=> [CHI-98] Add version dropdown to docs header

src/chi/components/buttons/buttons.scss
Added support for different tones to each type and color definition for buttons.
Cleaned up -dark color patch. There are small differences in the shadows generated for this button but they are almost inappreciable and now is consistent with other button definitions. Please validate this.
Annotated legacy code.
=> [CHI-167] Refactor colors in button sass file

src/chi/javascript/components/expansion-panel.js, src/website/views/javascript/expansion-panel.pug
Fixed a bug that prevented a button to work when the button contains an icon.
Added toggle action documentation.
Fixed disable detection on construct. If an element was disabled and became active, it entered in the double state of active and disable at the same time. 
Fixed free mode documentation. Example expansion panel had id example4 and the JavaScript example code looked for #example5. 
@davidojedacl Please review.
=> [CHI-178] Fix expansion panel bugs

src/chi/components/html-select/html-select.scss, src/chi/components/input-text/_input-text-variables.scss, src/chi/components/input-text/_input.scss
Updated left padding to 0.75rem for select and inputs of type text for all sizes.
Cleaned up variables utilization for select and input of type text.
=> [CHI-174] Fix text input and select padding inconsistency

src/chi/components/avatars/avatars.scss, src/website/views/components/avatar.pug, test/chi/components/avatar.pug
Now, the **minimum border width is 0.0625rem** equivalent to 1px. So now, from xs to md sizes the border width is 0.0625rem, lg: 0.08333rem, xl: 0.125rem, xxl: 0.1666rem. 
Ass needed for the order checkout flow templates, I have added transparent and inverse versions for avatars. Inverse icons automatically have transparent background, so there is no need to use both at the same time. All possibilities are shown in the test pages of the avatar component.
=> [CHI-181] Add transparent and inverse versions for avatars

src/chi/javascript/components/expansion-panel.js, src/website/views/javascript/expansion-panel.pug
Added the ability to override active, done, pending, disabled, toggle, next, previous default actions.
Now setting state active to a previous step doesn't change any previously set done states.
Updated Expansion Panel documentation.
=> [CHI-185] Change Expansion Panel Stepped Group Behaviour

src/chi/components/input-text/_input-floating-label.scss, src/chi/components/input-text/_input.scss
As there were no line-height defined for the label, it inherited the container line height. So whenever the floating label input component was inside an element with modified line-height, it didn't look good.
=> [CHI-201] Fix line-height bug in Floating Label component

src/chi/components/tooltip/tooltip.scss, src/chi/javascript/components/tooltip.js, src/chi/javascript/core/util.js, src/website/views/javascript/tooltip.pug
@mattnickles, please read before reviewing. 
Goods: CSS only solution. 
Bads: **Had to increase the left and right padding**.
There is an unofficial CSS solution (line-clamp), but it is not supported by IE nor Firefox. 
There are JavaScript solutions, but they are based on calculations that may require CPU and add listeners to viewport modifications.
=> [CHI-177] Update truncating logic in tooltips.

src/chi/components/tabs/tabs.scss, src/website/assets/scripts/chi-docs.js, src/website/assets/styles/_docs-container.scss, src/website/layouts/partials/aside.pug
Updated. 
Please @mattnickles , @jllr . There are some things I don't like relating this implementation. I need feedback:
- Inner list items now have a margin-bottom the didn't have. It is because the use of size -lg in the component. Should I remove this margin in our tabs component? Should I just fix this in documentation nav? Or should I left this as is in this pull request?
- When navigating to a 1st level element, the border slides to this element and then, the first list item inside it appears and is selected, so the border jumps to it. This is because the inner list items are hidden in first place. I can resolve this problem in several ways:
- Making all the elements visible since the beginning (not good as there are a lot)
- Creating a new vertical menu (not using tabs but the …
=> [CHI-160] Update documentation nav with our new tab component

src/chi/components/avatars/avatars.scss, src/website/views/components/avatar.pug, test/chi/components/avatar.pug
@mattnickles @jllr  This PR replace [CHI-XXX] Change Avatar Color Inverse -mint color tone and solve this comment of @mattnickles  : Colors need to follow a consistent tone and Mint 40 text on white doesn't meet our accessibility requirements. Let's revert and add support for -primary and -secondary classes instead. -secondary is intended for black backgrounds and its value is Mint 40.
=> [CHI-219] Add primary and secondary color support to avatars

src/custom-elements/package.json, src/custom-elements/stencil.config.ts, src/website/views/custom-elements/overview.pug, tasks/watch.js
Now stencil build is closer to default and chi watch task copies the bundle into the chi project.
=> [CHI-XX] Fix to allow custom elements render on chi documentation.

src/chi/components/buttons/buttons.scss, src/website/views/components/button.pug
- Deemphasize danger buttons
- Remove pill outline examples
- Remove color styles from pill example
- Document when to use light vs dark buttons
- Document inverse buttons
- Improve example layout to illustrate buttons on both light and dark backgrounds
@jllr @davidojedacl While updating the documentation I discovered we're missing inverse support for base and outline button styles. Can you fix? Details are in CHI-237
=> [CHI-238] Improve button documentation

src/website/views/components/button-group.pug, src/website/views/components/button.pug, src/website/views/components/footer.pug
- Fixed Button tag example which was not wrapping and floating outside of the container
- Added margin to button examples to provide sufficient spacing when stacked on mobile
- Updated footer examples with correct links
=> [CHI-277] Fix documentation example bugs

src/chi/components/buttons/buttons.scss
Teams overriding Chi's default font with Maison Neue are experiencing issues with the button component still rendering in Open Sans. I've removed the redundant font-family from the button component so it properly inherits the font-family value defined on .chi.
=> [CHI-376] Removed font family property from button component

src/website/assets/styles/_docs-container.scss, src/website/views/components/forms/checkbox.pug, src/website/views/components/picker.pug, src/website/views/custom-elements/progress.pug
The selectors in docs-container are temporary. Will update with the release of text/heading size utility classes
=> [PE-3859] Fixed inconsistent headings on getting started page

src/chi/components/date-picker/date-picker.scss, src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx, src/custom-elements/src/components/label/label.scss, src/custom-elements/src/components/label/label.tsx, src/website/layouts/partials/header.pug, src/website/views/custom-elements/date-picker.pug, src/website/views/custom-elements/overview.pug
@jllr @mattnickles @dani-cl-madrid 
In order to let the user define `for=""` and `id=""` attributes in a clean way, I added support of `<chi-label>` CE.
This approach is 100% clean and the markup is simple.
```
<chi-label for="date">Date</chi-label>
<chi-date-picker id="date"></chi-date-picker>
```
For now we can use this CE to fix the accessibility issue. In future we will add attributes like icon, size, etc.
https://ctl.atlassian.net/browse/PE-3835
=> [PE-3835] Fix date picker input id attribute accessibility issue

src/chi/javascript/components/drawer.js, src/chi/javascript/components/modal.js
After investigating the issue of disappearing `-disableScroll` class on Modal component figured out that there was a conflict between DOM events of Modal and Drawer components JSs.
With this fix, the -disablescroll class presence on BODY depends on state of Modal and Drawer `if(!this._shown)`
But I wonder if we should assign individual classes to each like:
`-disableScrollModal` and `-disableScrollDrawer`
Could there be a case when both of the components are "open"? Like a drawer inside of an open modal?
https://ctl.atlassian.net/browse/PE-4159
=> [PE-4159] Fixed disableScroll of drawer and modal

src/chi/javascript/components/sidenav.js
A bugged found by Cristina.
Clicking on A subtab which contains child elements like `span` or icon fails to close of the currently open drawer.
This fix must be merged
=> FIX---Close drawer when sidenav subtab has child element

tasks/build-website-scripts.js
@jllr @dani-cl-madrid @mattnickles 
[PE-3841] This ticket has been resolved because we were unable to reproduce the Parsing error @mattnickles encountered.
I tried Chi build command to make sure that the Build Gulp tasks work as supposed and found the same error.
This fixes the Parsing error.
https://ctl.atlassian.net/browse/PE-3841
[PE-3841]: https://ctl.atlassian.net/browse/PE-3841
=> FIX-- Module export parsing err when chi build runs

src/chi/components/drawer/drawer.scss, src/custom-elements/docs/docs.json
This hack is necessary to fix the position of X (close) button of the drawer component in IE11.
With the default position fixed it's invisible
@jllr @mattnickles
=> [FIX] Fixed drawer close button in IE11

package.json, scripts/chi.js, src/custom-elements/docs/docs.json, tasks/build-chi-scripts-amd.js, tasks/build-chi-scripts.js
Added support of adding Copyright text to chi-icon.js and chi.css when Chi build runs.
Assets related to Web components are generated by Stencil and it will require some additional reconstruction.
I think we can merge these changes for the next release and afterwards work on adding copyright to Web component related assets.
https://ctl.atlassian.net/browse/PE-4312
=> [PE-4312] Added copyright  to chi-icon.js, chi.css

src/website/assets/scripts/chiVersionCheck.js, src/website/assets/styles/_docs-container.scss, src/website/layouts/partials/header.pug
--PLEASE DON'T MERGE YET--
(`https://assets.ctl.io/chi/` --> `https://assets.ctl.io/chi/${currentVersion}`), since apparently browser also caches `redirection` of the base URL
Unable to reproduce the error we saw on `https://assets.ctl.io/chi/latest` URL. I Will investigate it.
@mattnickles @jllr @dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4295
=> [PE-4295] Fix versioning banner redirection and reduce version dropdown number of versions

src/chi/components/card/card.scss, src/custom-elements/docs/docs.json, src/website/views/components/card.pug
https://ctl.atlassian.net/browse/PE-4334
=> [PE-4334] Added support of a-card__icon class

src/chi/components/sidebar/sidenav.scss, src/chi/javascript/components/sidenav.js, src/chi/javascript/core/util.js, src/website/views/javascript/sidenav.pug
@dani-cl-madrid @jllr @mattnickles
https://ctl.atlassian.net/browse/PE-4336
=> [PE-4336] Improved Global Nav selecting  behavior

src/chi/components/picker/picker-groups.scss, src/chi/components/picker/picker.scss, src/website/views/components/picker-group.pug, src/website/views/components/picker.pug
**Picker component**
1. Added support of changing background color of picker with :active checkbox (Switching between pickers using tab / shift + tab keys, checking a picker with space key)
2. Improved name attributes of all the examples
**Picker Group component**
1. Added support of changing background color of the first of Picker Group (when navigation to it using tab key from some other focused element before Picker group) or last element (when navigation to it using shift + tab from some other focused element that comes after Picker group);
Switching between elements of Picker Group works (Using arrow keys, native behavior of switching between radio inputs. Please see: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_radio)
2. Changed name attributes of all the …
=> [PE-4377] Fixed Picker & PickerGroup keyboard trap

src/custom-elements/docs/docs.json, src/custom-elements/src/components/drawer/drawer.tsx, src/custom-elements/src/components/popover/popover.tsx
Changed Popover and Drawer CE Event names to match the camel case convention
https://ctl.atlassian.net/browse/PE-4370
@dani-cl-madrid @jllr @mattnickles
=> [PE-4370] Changed Popover Drawer CE event names

src/website/assets/scripts/chi-docs.js, src/website/layouts/default.pug
- Fixed targetting of anchor generator
- Fixed a bug related `-active` class management when navigating to an anchor element within documentation tabs
https://ctl.atlassian.net/browse/PE-4664
=> [PE-4664] Fixed anchor tab script in chi-docs

src/chi/javascript/components/dropdown.js
This is a fix for a console error `this._popper.update() not a a function`
@dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4742
=> [PE-4742] Fixed broken Dropdown data-target

CHANGELOG.md, package.json, src/chi/utilities/sizing.scss, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/assets/styles/_docs-container.scss, src/website/layouts/partials/header.pug, src/website/layouts/partials/sidenav.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
**Components**
- Fixed: Sizing utility values did not have enough specificity to override default component sizes.
- Fixed: Sizing utility support for width auto was removed when we added 5% increment rules.
**Documentation**
- Changed: Removed Design Kit button from docs sidenav as GitHub renders private repos as 404 pages and most do not have permissions to view.
=> [PE-4815] Fixed specificity bug in sizing utility

src/chi/javascript/components/tab.js
Currently, this markup of tabs work:
```
<ul class="chi-tabs">
<li class="-active"><a href="#">Active Tab</a></li>
<li><a href="#">Tab Link</a></li>
<li><a href="#">Tab Link</a></li>
</ul>
```
But if we break `<li>` like this:
```
<ul class="chi-tabs">
<li class="-active">
<a href="#horizontal-base-1">Active Tab</a>
</li>
<li><a href="#">Tab Link</a></li>
<li><a href="#">Tab Link</a></li>
</ul>
```
It breaks (as you can see here: https://codepen.io/janibolkvadze/pen/QWjppoE).
It happens because `getAssociatedTabPanel` method uses `childNodes` which in case of this markup returns: `[#text, Anchor, #text]`
So I added validation to this method when using `Util.getTarget(tab.childNodes[i])` which expects an `<a>` to get its `href`.
@dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4894
=> [PE-4894] Fixed Tab component JS structure issue

src/custom-elements/src/components/number-input/number-input.tsx
https://ctl.atlassian.net/browse/FSPE-6111
Currently, Chi Number Input adjusts the value when the user manually types a value below Min or above Max.
This codepen includes temporal `ux-chi-ce.esm.js` from the instances of this PR including the fix for the issue.
https://codepen.io/janibolkvadze/pen/wvGbvQq
@dani-cl-madrid @SergioQCL @jllr @mattnickles
=> [FSPE-6111] Fixed Number Input min-max validation

src/chi/components/input-number/_input.scss
This change is needed to support width utility classes on `chi-number-input` for grid compatibility.
https://ctl.atlassian.net/browse/FSPE-6114
=> [FSPE-6114] Changed number input width value for grid compatibility

src/chi/components/picker/_horizontal-picker-groups.scss, src/chi/components/picker/picker-groups.scss, src/website/views/components/picker-group/_examples.pug, test/chi/components/picker-group.pug
Fixed bug in picker groups which prevented child items from stretching and filling their parent containers vertical space.
https://ctl.atlassian.net/browse/FSPE-6125
=> [FSPE-6125] Fixed picker group stretch behavior

CHANGELOG.md, src/chi/components/alert/_alert-common.scss, src/chi/skeletons/brand.scss, src/chi/skeletons/button.scss, src/chi/skeletons/progress.scss, src/website/views/getting-started/whats-new.pug, src/website/views/templates/portal.pug
https://ctl.atlassian.net/browse/FSPE-6472
**Related to 3.3.0**
* Fixed: Alert Modal in Templates/Portal was rendering incorrectly in IE11.
**Unrelated to 3.3.0**
* Fixed: Alert content text was not wrapping correctly in IE11.
* Fixed: Brand web component skeleton was rendering with the width and height values of CenturyLink logo instead of Lumen logo.
* Fixed: Button web component skeleton rendered with an inconsistent display property that caused skeletons to stack instead of rendering inline.
* Fixed: Button web component skeleton was not respecting icon button sizes.
* Fixed: Progress web component skeleton rendered with a margin that caused the component to jump after preloading.
=> [FSPE-6472] Skeleton preloader and IE11 bug fixes

src/chi/components/input-wrapper.scss, src/chi/components/radio/radio.scss, src/custom-elements/docs/docs.json, src/website/views/components/forms/radio-button/_examples.pug, src/website/views/components/forms/select/_examples.pug
* Added: Radio button documentation now includes examples for Base, Checked, Disabled, Required, Optional, Help, and Error.
* Added: Select documentation now includes examples for Required, Optional, Help, Message, and Error.
* Changed: Further reduced size of chi.css by simplifying radio.scss.
* Changed: `chi-label__wrapper` and `chi-label__help` can now be rendered outside of `chi-form__item`. This was necessary to support `legend` elements which exist outside of `chi-form__item`.
=> [FSPE-6492] Improved radio and select docs

src/chi-vue/.browserslistrc, src/chi-vue/.eslintrc.js, src/chi-vue/.gitignore, src/chi-vue/README.md, src/chi-vue/babel.config.js, src/chi-vue/package.json, src/chi-vue/public/index.html, src/chi-vue/src/App.vue, src/chi-vue/src/components/drawer/drawer.tsx, src/chi-vue/src/components/pagination/pagination.tsx, src/chi-vue/src/constants/classes.ts, src/chi-vue/src/constants/constants.ts, src/chi-vue/src/constants/events.ts, src/chi-vue/src/constants/types.ts, src/chi-vue/src/main.ts, src/chi-vue/src/shims-tsx.d.ts, src/chi-vue/src/shims-vue.d.ts, src/chi-vue/src/utils/ThreeStepsAnimation.ts, src/chi-vue/src/utils/utils.ts, src/chi-vue/src/views/DrawerView.vue, src/chi-vue/src/views/PaginationView.vue, src/chi-vue/tsconfig.json
--- Initial Implementation ---
1. Introduced Vue Class Component architecture based on TypesCript syntax.
2. Implemented native Vue reusable **Pagination** component supporting:
All the available options are consistent with Chi Pagination web component.
3. Created Pagination component view with all the available options.
4. Implemented native Vue reusable **Drawer** component supporting:
5. Created Drawer component View with available options.
The implementation does not yet support corresponding Gulp Build tasks.
Please run `npm run serve` in the directory: `/src/chi-vue` and navigate to `http://localhost:8080/` in your browser.
@dani-cl-madrid @SergioQCL @jllr @mattnickles 
https://ctl.atlassian.net/browse/FSPE-5842
https://ctl.atlassian.net/browse/FSPE-5838 …
=> [FSPE-5842] Added support of native Vue Chi Pagination & Drawer

src/website/assets/styles/_docs-container.scss, src/website/layouts/default.pug, src/website/views/components/card/_examples.pug, src/website/views/components/data-table/index.pug, src/website/views/components/dropdown/_examples.pug, src/website/views/components/expansion-panel/_examples.pug, src/website/views/components/footer/_examples.pug, src/website/views/components/footer/index.pug, src/website/views/components/forms/number-input/_examples.pug, src/website/views/components/forms/toggle-switch/_examples.pug, src/website/views/components/header/_examples.pug, src/website/views/components/header/index.pug, src/website/views/components/sidenav/_examples.pug, src/website/views/components/stat/_examples.pug
https://ctl.atlassian.net/browse/FSPE-6615
Related to #764 [FSPE-6598]
* Removed remaining duplicate IDs in doc examples from the following pages: Card, Dropdown, Expansion Panel, Footer, Header, Sidenav, Stat
* Removed unnecessary ID from toggle switch span tag.
* Changed Number Input attribute order.
* Increased grid container width on header and footer doc pages.
[FSPE-6598]: https://ctl.atlassian.net/browse/FSPE-6598
=> [FSPE-6615] Removed remaining duplicate IDs

src/chi/javascript/components/tooltip.js, src/chi/javascript/constants/constants.js, src/chi/javascript/core/chi.js, src/website/views/components/tooltip/_examples.pug
@dani-cl-madrid @SergioQCL @mattnickles @jllr 
https://ctl.atlassian.net/browse/FSPE-6932
=> [FSPE-6932] Add support of removing Tooltip delay when navigating between close Tooltips

src/chi/javascript/components/drawer.js, src/chi/javascript/components/dropdown.js, src/chi/javascript/components/popover.js, src/chi/javascript/components/tooltip.js, src/website/views/components/drawer/_properties.pug, src/website/views/components/dropdown/_properties.pug, src/website/views/components/popover/_properties.pug, src/website/views/components/tooltip/_properties.pug
https://ctl.atlassian.net/browse/FSPE-6587
=> [FSPE-6587] Add support of missing event emission of chi.js components
