CenturyLinkCloud/ux-chi

CHANGELOG.md, src/css/utilities/display.scss
@jsmecham Only thing that bugs me is it's outputting 9 media queries (one per type) instead of 5 media queries (one per size). Is there any way to achieve the following:
```
@media only screen and (max-width:575px) {
.chi .-d-xs--none {
display: none
}
.chi .-d-xs--inline {
display: inline
}
.chi .-d-xs--inline-block {
display: inline-block
}
.chi .-d-xs--block {
display: block
}
.chi .-d-xs--table {
display: table
}
.chi .-d-xs--table-cell {
display: table-cell
}
.chi .-d-xs--table-row {
display: table-row
}
.chi .-d-xs--flex {
display: -webkit-box;
display: -ms-flexbox;
display: flex
}
.chi .-d-xs--inline-flex {
display: -webkit-inline-box;
display: -ms-inline-flexbox;
display: inline-flex
}
}
```
versus the current:
```
@media only screen and (max-width:575px) {
.chi .-d-xs--none { …
```
=> Added display utility classes

src/chi/components/modal/modal.scss, src/website/assets/styles/grid.scss, src/website/views/components/alerts.pug, src/website/views/components/buttons.pug, src/website/views/components/forms/radio-buttons.pug, src/website/views/components/forms/range-sliders.pug, src/website/views/components/forms/toggle-switch.pug, src/website/views/foundations/grid.pug, src/website/views/index.pug, src/website/views/utilities/display.pug
- Improved instructions for adding chi class on Getting Started
- Improved banner example on Components/Alerts
- Addressed a number of minor style bugs I found testing in Firefox 48-61 and Microsoft Edge 15-17
=> Fixed minor style bugs in documentation

src/chi/components/tables/tables.scss, src/website/views/components/tables/_common.pug, src/website/views/components/tables/index.pug
Bug fix for: https://github.com/CenturyLinkCloud/ux-chi-design/issues/20
=> Removed inline styles from table examples

src/chi/components/badge/badge.scss, src/chi/utilities/spacing.scss, src/chi/variables.scss, src/website/views/components/badge.pug, test/chi/components/badges.pug
https://elasticbox.atlassian.net/browse/CHI-34
=> [CHI-34] Badge component improvements

src/chi/components/_input-wrapper.scss, src/website/views/components/forms/checkbox.pug, src/website/views/components/forms/file-input.pug, src/website/views/components/forms/number-input.pug, src/website/views/components/forms/radio-button.pug, src/website/views/components/forms/range-slider.pug, src/website/views/components/forms/select.pug, src/website/views/components/forms/text-input.pug, src/website/views/components/forms/textarea.pug, src/website/views/components/forms/toggle-switch.pug, test/chi/components/checkbox.pug, test/chi/components/radio.pug
@mattnickles 
https://elasticbox.atlassian.net/browse/CHI-82
=> [CHI-82] Rename a-formGroup from atom a- to molecule m-

src/chi/components/breadcrumb/breadcrumb.scss, src/chi/components/breadcrumb/icon-chevron-right.svg, src/website/views/components/breadcrumb.pug, test/chi/components/breadcrumb.pug
@mattnickles @jllr I have a doubt related base font size. If i don't use -text and I put it in the breadcrumb class the base font size then the text modifiers don't work
=> [CHI-70] Add breadcrumb component.

src/website/views/components/avatar.pug, src/website/views/components/tabs.pug, test/chi/components/avatar.pug
Fixed lint errors related to tabs and avatars.
=> [CHI-85] Fix lint errors related to tabs and avatars

src/chi/components/tabs/tabs.scss, src/website/views/components/tabs.pug, test/chi/components/tabs.pug
=> [CHI-86] Fix bug related to icons in horizontal tabs

src/chi/components/brand/brand.scss, src/website/views/components/brand.pug, test/chi/components/brand.pug
=> [CHI-88] Add Brand component

src/chi/components/divider/divider.scss, src/website/views/components/divider.pug, test/chi/components/divider.pug
@mattnickles @jllr Maybe can use footer small in cards instead divider
=> [CHI-71] Add divider component

src/chi/components/spinner/spinner.scss
=> [CHI-91] Fix Spinner support in IE

src/website/views/components/avatar.pug
Replaced SVG example with WebFont examples. 
@mattnickles, maybe I am missing something. I replaced the SVG examples with the WebFont code and everything seems to work right. Can you send me any examples of what you saw? Thank you.
=> [CHI-90] Fix alignment of icon avatars using web font

src/chi/utilities/border.scss, src/website/views/utilities/border.pug
Added responsive support to border sizes and border colors.
=> [CHI-106] Add responsive support to border utility.

src/chi/utilities/color.scss, src/website/views/utilities/color.pug
=> [CHI-102] Add color utility

src/website/views/utilities/color.pug
=> Clean-obsolete-code

src/chi/components/breadcrumb/breadcrumb.scss
=> [CHI-117] Fix lint warnings in Breadcrumb sass file

src/website/assets/scripts/chi-docs.js, src/website/assets/styles/chi-docs.scss
Add copy to clipboard functionality to documentation examples
=> [CHI-118] Add copy to clipboard functionality to documentation examples

src/chi/foundations/typography/typography.scss, src/chi/variables.scss, src/website/assets/scripts/chi-docs.js, src/website/assets/styles/chi-docs.scss, src/website/assets/styles/icons.scss, src/website/views/components/drawer.pug, src/website/views/components/icon.pug, src/website/views/foundations/typography.pug, src/website/views/utilities/text.pug
- Added base/body and white text color utilities
- Removed inverse text color from documentation to eliminate confusion with white
- Moved most utility examples from foundations/typography to utilities/text
=> [CHI-143] Added base/body and white text color utilities

src/website/views/getting-started/browsers-devices.pug
- Added basic browser support page
- Defined supported browser versions and tested in browserstack to verify.
@jllr Encountered several bugs with tables. I've created a ticket (CHI-144) to resolve as I'm unable to center anything inside `<th>` or `<td>` tags.
=> [CHI-114] Browser support page

src/chi/components/buttons/buttons.scss, src/chi/components/input-file/input-file.scss, src/chi/utilities/zindex.scss, src/chi/variables.scss, src/website/views/utilities/zindex.pug
I didn't add responsive support as I think it is not necessary. @mattnickles, if it is, tell me, and I will do it in a moment.
=> [CHI-131] Add z-index utility

src/chi/components/backdrop/backdrop.scss, src/chi/components/drawer/drawer.scss, src/chi/javascript/drawer.js, src/chi/javascript/dropdown.js, src/chi/javascript/index.js, src/chi/javascript/util.js, src/website/views/javascript/drawer.pug
Added javascript logic for drawer component
=> [CHI-142] Add javascript logic for drawer component

src/website/views/components/drawer.pug, src/website/views/components/modal.pug, src/website/views/javascript/drawer.pug
- Replaced inline styles with new position and z-index utility
- Updated drawer documentation examples
=> Updated documentation examples

CHANGELOG.md, src/chi/components/alert/_alert-common.scss, src/chi/components/badge/badge.scss, src/chi/components/checkbox/checkbox.scss, src/chi/components/html-select/html-select.scss, src/chi/components/input-file/input-file.scss, src/chi/components/input-number/_input.scss, src/chi/components/input-text/_input.scss, src/chi/components/modal/modal.scss, src/chi/components/radio/radio.scss, src/chi/components/textarea/_input-textarea.scss, src/chi/components/toggle-switch/toggle-switch.scss, src/chi/foundations/typography/typography.scss, src/website/assets/styles/chi-docs.scss, src/website/views/getting-started/browsers-devices.pug, src/website/views/getting-started/index.pug, src/website/views/getting-started/whats-new.pug, tasks/build-website-views.js
- Updated Changelog
- Added Changelog page to documentation
Other improvements:
- Added scale animation to radio buttons and checkboxes
- Improved box-shadow on radio buttons, checkboxes, and toggle switches
- Updated border-radius values with the border-radius variable
=> [CHI-99] Added Changelog page to documentation

src/chi/components/steps/steps.scss, src/website/views/components/steps.pug, test/chi/components/steps.pug
=> [CHI-79] Add steps component

src/chi/components/buttons/buttons.scss
=> [CHI-149] Fix flat button  hover padding bug

src/chi/components/buttons/buttons.scss
Bug also affected active and focus states so I've removed the duplicate padding from there as well.
=> [CHI-149] Fix flat button hover padding bug

src/chi/components/tabs/tabs.scss
=> [CHI-154] Update font size of tab component

src/chi/components/input-number/_input-wrapper.scss, src/chi/javascript/number-input.js, src/chi/javascript/util.js
Some JavaScript didn't work and has been added support for isInteger and createEvent in util.js.
Had to add height to buttons because Internet Explorer only support up to two decimals in rem, and sum of element + 2xpadding + 2xborder didn't match desired height.
=> [CHI-159] Added support for number input buttons in internet explorer.

src/chi/javascript/drawer.js
=> [CHI-164] Fix drawer animation

src/chi/components/price/price.scss, src/website/views/components/price.pug, test/chi/components/price.pug
=> [CHI-158] Add price component - I added 2 versions to compare

src/chi/components/buttons/buttons.scss, src/chi/components/dropdown/dropdown.scss, src/chi/components/html-select/icon-chevron-thin-down-inverse.svg, src/chi/components/html-select/icon-triangle-down-inverse.svg
=> [CHI-165] Fix trigger icon color within inverse buttons

backstop-non-responsive.json, src/chi/components/range-slider/range-slider.scss, src/chi/javascript/floating-label.js, src/chi/javascript/index.js, src/chi/javascript/number-input.js, src/chi/javascript/range-slider.js, src/chi/javascript/tab.js, src/chi/javascript/tooltip.js, src/website/views/components/forms/number-input.pug, src/website/views/components/forms/range-slider.pug, src/website/views/javascript/range-slider.pug, test/chi/components/range-slider.pug
Uncompleted feature. 
JavaScript-dependant consistent design for the range slider for WebKit browsers. 
Two approaches for the new range slider design with labels below it (please, check this @mattnickles )
=> [CHI-157] Add javascript range slider component

src/chi/components/card/card.scss, src/website/views/components/card.pug, test/chi/components/card.pug
=> [CHI-116] Add empty and active states to card component

src/chi/components/dropdown/dropdown.scss, src/website/views/components/dropdown.pug
Added hover support to dropdowns and written documentation.
=> [CHI-151] Add dropdown example which initiates on hover to docs

src/chi/utilities/position.scss, src/website/views/utilities/position.pug
=> [CHI-113] Extend fixed support in position utility

src/chi/components/range-slider/range-slider.scss
=> [CHI-168] Fix range slider internet explorer tooltip display

src/chi/components/progress-bar/progress-bar.scss, src/website/views/components/progress-bar.pug, test/chi/components/progress-bar.pug
=> [CHI-127] Add progress-bar component

src/chi/components/_input-wrapper.scss
=> [CHI-169] Fix border-bottom-message-checkbox-list

src/chi/components/header/header.scss, src/website/layouts/partials/header.pug
=> [CHI-170] Fix z-index issues in component examples

src/chi/javascript/components/auxiliary/overflow-menu.js, src/chi/javascript/components/navigation.js, src/website/views/javascript/expansion-panel.pug, src/website/views/javascript/tabs.pug
Fixed expansion-panel documentation javascript file path. 
Changed unsupported horizontal ellipsis character to three dots. 
Enable back tab functionality and fixed links.
=> Fix/chi xx fix 0.9.1 release bugs

src/chi/components/input-text/_input-floating-label.scss, src/chi/javascript/components/floating-label.js, src/website/views/javascript/floating-label.pug
Added floating label support for select boxes.
=> [CHI-173] Floating label in select boxes

src/chi/components/navigation/_navigation-dropdown.scss, src/chi/components/navigation/_navigation-tabs.scss
Added support for small and large tabbed dropdowns.
=> [CHI-175] Add small and large support to tabs.

src/chi/components/picker/picker.scss, src/website/views/components/picker.pug
@mattnickles @jllr I added checkbox with description in the picker component to match with the order checkout flow template
=> [CHI-180] Add picker with secondary description

src/website/assets/styles/show-example.scss, src/website/views/foundations/grid.pug, src/website/views/utilities/display.pug, src/website/views/utilities/flex.pug, src/website/views/utilities/sizing.pug, src/website/views/utilities/text.pug
@mattnickles @jllr  I have unified all the green divs that are used as a container for an example in the documentation
=> [CHI-182] backgrounds in documentation div examples

src/website/views/components/brand.pug, src/website/views/components/button.pug
=> [CHI-186] Unify size labels in documentation

src/chi/components/buttons/buttons.scss
=> [CHI-188] Change secondary outline button hover color to black

src/chi/components/buttons/_horizontal-button-groups.scss, src/chi/components/buttons/_vertical-button-groups.scss, src/website/views/components/button-group.pug, test/chi/components/button-horizontal-groups.pug, test/chi/components/button-vertical-groups.pug
=> [CHI-58] Document Additional button group sizes

src/website/views/components/footer.pug, test/chi/components/footer.pug
@mattnickles @jllr  Remove divider margin on the footer with divider to center vertical the content later
=> [CHI-189] Reduce footer divider margin

package.json, tasks/build-test-fixtures.js, tasks/build-test.js, tasks/serve.js
Restored index.html in tests page.
=> [CHI-197] Restore index.html in test pages. 

src/chi/components/tabs/tabs.scss
=> [CHI-191] Tab component is using incorrect text color

src/website/views/foundations/color.pug
=> [CHI-195] Grey 70 value on color page is incorrect

src/chi/components/buttons/buttons.scss
=> [CHI-192] Remove white background from outline button hover states

src/chi/components/buttons/buttons.scss, src/website/views/components/button.pug, test/chi/components/buttons.pug
=> [CHI-194] Add fluid support to button component

tasks/serve.js
Navigation, scroll and clicks were being synced. Now this functionality has been removed.
=> [CHI-202] Stop syncing different browsers connected to same devenv.

src/website/views/utilities/flex.pug
=> [CHI-203] Fix height bug in flex documentation examples

src/chi/components/modal/modal.scss, src/website/views/components/modal.pug, test/chi/components/modals.pug
=> [CHI-200] Add subtitle support to modal component

src/chi/components/input-text/_input.scss
=> [CHI-206] Remove clear field X inside inputs in ie11 and edge

src/website/views/templates/fieldset.pug
=> [CHI-204] Add Fieldset template

src/chi/components/card/card.scss, src/chi/components/toggle-switch/toggle-switch.scss
…ak property only in p tags
@mattnickles @jllr
=> [CHI-208] Prevent toggle switch text from wrapping within card components

src/chi/components/popover/popover.scss, src/chi/components/tooltip/tooltip.scss, src/chi/javascript/components/drawer.js, src/chi/javascript/components/number-input.js, src/chi/javascript/components/popover.js, src/chi/javascript/components/range-slider.js, src/chi/javascript/components/tooltip.js, src/chi/javascript/core/chi.js, src/chi/javascript/core/component.js, src/chi/javascript/core/util.js, src/chi/javascript/index.js, src/website/assets/styles/chi-docs.scss, src/website/views/components/popover.pug, src/website/views/javascript/popover.pug, src/website/views/javascript/tooltip.pug
Added a popover component. This is a branch of https://github.com/CenturyLinkCloud/ux-chi/pull/192 so this pull request includes that changes.
=> [CHI-75] Add popover component

src/chi/components/drawer/drawer.scss, src/chi/components/footer/footer.scss, src/chi/components/sidebar/sidebar.scss, src/chi/components/tabs/tabs.scss, src/chi/foundations/typography/typography.scss, src/chi/javascript/components/drawer.js, src/chi/javascript/components/sidebar.js, src/chi/javascript/components/tab.js, src/chi/javascript/core/component.js, src/chi/javascript/core/util.js, src/chi/javascript/index.js, src/chi/mixins.scss, src/chi/variables.scss, src/website/assets/styles/_docs-container.scss, src/website/views/components/sidebar.pug, src/website/views/javascript/drawer.pug, src/website/views/javascript/sidebar.pug, tasks/build-chi-scripts-amd.js, tasks/build-chi-scripts.js, tasks/build-website-scripts.js, tasks/constants.js
Added main navigation component AKA sidebar.
=> [CHI-109] Add main navigation component (sidebar)

src/chi/components/tabs/tabs.scss
Need this for Main Navigation component and for CHI-172.
=> [DON'T MERGE][CHI-XX] Remove implicit height on vertical tabs border.

src/chi/components/sidebar/sidenav.scss, src/chi/javascript/components/drawer.js, src/chi/javascript/components/sidenav.js, src/chi/javascript/core/chi.js, src/chi/javascript/index.js, src/website/views/components/sidenav.pug, src/website/views/javascript/sidenav.pug
Sidebar renamed to Sidenav.
Additional fixes.
@mattnickles , please review.
=> [CHI-211] Sidebar renamed to Sidenav.

src/chi/components/_input-wrapper.scss, src/chi/components/input-text/_input-floating-label.scss, src/chi/components/input-text/_label.scss, src/chi/components/input-text/input-text.scss, src/website/views/components/forms/select.pug, src/website/views/components/forms/text-input.pug, src/website/views/components/forms/textarea.pug, test/chi/components/input-text.pug, test/chi/components/textarea.pug
=> [CHI-207] Add default label styles

src/chi/components/_input-wrapper.scss, src/chi/components/picker/picker.scss
=> [CHI-XXX] Fix label font weight bug

src/website/views/components/button-group.pug
=> [CHI-216] remove unnecessary examples from button-group size docs

src/chi/components/modal/modal.scss, src/website/views/components/modal.pug, test/chi/components/modals.pug
=> [CHI-217] Modal component is misaligned

src/chi/components/header/header.scss
=> [CHI-218] Fix misaligned header content in IE11

src/chi/components/modal/modal.scss, src/chi/utilities/sizing.scss, src/website/views/components/modal.pug, src/website/views/utilities/sizing.pug
=> [CHI-215] Add scrolling example to modal component docs

src/chi/components/divider/divider.scss, src/chi/utilities/sizing.scss, src/website/views/components/divider.pug, test/chi/components/divider.pug
=> [CHI-221] Add color bar divider component

src/website/views/templates/fieldset.pug
=> [CHI-231] Improve Fieldset template markup

src/chi/components/buttons/buttons.scss
=> [CHI-233] Fix missing active state on flat buttons

src/chi/components/buttons/buttons.scss
=> [CHI-234] Fix incorrect icon color in outline secondary button hover states

src/chi/index.scss, src/chi/utilities/anchor.scss
=> [CHI-XXX] Fix anchor bug related chi namespace

src/chi/components/modal/modal.scss, src/chi/javascript/components/modal.js, src/website/views/javascript/modal.pug
=> [CHI-235] Fix IE11 Modal bugs

src/website/layouts/partials/aside.pug
=> [CHI-236] Disable Custom Element tab

src/chi/components/buttons/buttons.scss, src/website/views/components/button.pug
=> [CHI-237] Buttons are rendering incorrectly

src/chi/components/buttons/buttons.scss
=> [CHI-XXX] Box shadow buttons bug

src/website/views/foundations/color.pug
=> [CHI-241] Add color Palettes accordion-mode-expansion-panel

src/chi/components/sidebar/sidenav.scss
=> [CHI-242] Sidenav tabs not showing in IE11

src/website/layouts/partials/header.pug
@mattnickles @jllr  i included Subject text in the email ("Question about CHI library")
=> [CHI-244] Add support link to documentation

src/chi/components/picker/picker.scss
=> [CHI-245] Fix picker component text overflow bug in IE11

src/chi/components/badge/badge.scss, src/website/views/components/badge.pug, test/chi/components/badges.pug
=> [CHI-248] Rename Light Badge To Muted

src/chi/components/tables/tables.scss
=> [CHI-252] Checkbox in table examples are not vertically centered

src/chi/javascript/components/auxiliary/sliding-border.js, src/chi/javascript/components/dropdown.js, src/chi/javascript/components/navigation/navigation-dropdown.js, src/chi/javascript/components/navigation/navigation-tab.js, src/website/views/javascript/tabs.pug
Fixed: Dropdown inside a dropdown in a navigation component now works correctly.
=> [CHI-255] Tabbed navigation bar bugs

src/chi/components/badge/badge.scss, src/chi/components/buttons/buttons.scss, src/chi/components/dropdown/dropdown.scss, src/website/layouts/partials/header.pug, src/website/views/components/badge.pug, src/website/views/components/button.pug, src/website/views/components/header.pug, src/website/views/templates/authentication.pug, test/chi/components/badges.pug, test/chi/components/buttons.pug
=> [CHI-251] Add support for light class

src/website/assets/scripts/chi-docs.js, src/website/layouts/partials/aside.pug
=> [CHI-XXX] Remove animation from aside

CHANGELOG.md, package.json, src/chi/components/activity/activity.scss, src/chi/components/alert/_bubble.scss, src/chi/components/alert/_toast.scss, src/website/layouts/partials/header.pug, src/website/views/components/icon.pug, src/website/views/custom-elements/overview.pug, src/website/views/getting-started/index.pug, src/website/views/getting-started/whats-new.pug, src/website/views/javascript/overview.pug
=> [CHI-XXX] Prepare 1-2-1 Release

src/website/views/templates/authentication.pug
=> [CHI-266] Update Authentication template with floating label inputs

src/chi/components/activity/activity.scss, src/website/views/components/activity.pug
=> [CHI-269] Add responsive behaviour to activity component

src/chi/components/tabs/tabs.scss
Fixed sliding border margin in lg tabs.
=> [CHI-273] Tab animation is broken for -lg size horizontal tabs

README.md, scripts/docker.sh, src/website/views/custom-elements/overview.pug, src/website/views/getting-started/index.pug
@jllr @dani-cl-madrid @juanmorra please review
=> [CHI-281] Create an alias to run all the commands

src/chi/components/buttons/buttons.scss
=> [CHI-279] Icon flat button is misplaced when active

src/chi/components/expansion-panel/expansion-panel.scss
=> [CHI-283] Active expansion panel step numbers are missing active styles

src/chi/components/header/header.scss
@davidojedacl @dani-cl-madrid 
https://elasticbox.atlassian.net/browse/CHI-284
=> [CHI-284] Fix flat icon button inconsistency

src/chi/components/input-number/_input-wrapper.scss
=> [CHI-289] Update number input size widths

src/chi/foundations/typography/typography.scss, src/chi/utilities/spacing.scss, src/website/views/components/dropdown.pug, src/website/views/components/forms/toggle-switch.pug, test/chi/components/dropdown.pug
!important added on text utilities classes
=> Add !important declaration in text

src/chi/components/steps/steps.scss
@mattnickles 
https://elasticbox.atlassian.net/browse/CHI-291
=> [CHI-291] Fix Active line in inverse step component

src/chi/components/spinner/spinner.scss
=> [CHI-307] Fix spinner in modal component

src/custom-elements/src/components/button/button.tsx, src/website/views/custom-elements/button.pug, test/chi/custom-elements/buttons.pug
Adding the new attributes to house both outline and flat properties of a button.
Deleted the old individual outline and flat props.
=> [CHI-XXX] adding new attribute variant for chi-button.

.prettierrc, package.json
Added Prettier config file for JavaScript and specially TypeScript files used in the Custom Elements version of Chi. Please @srinath-koneru, @SergioQCL review. This is the moment to propose any other desired rule. Once merged, rebase your PR and configure your code editors to use it. It should work with VSCode and WebStorm easily. I will ask @HectorGarciaAlvarez to add a test in the Jenkins to prevent non formatted files to be merged. TIA.
=> [CHI-XXX] Prettier configuration for JavaScript/TypeScript files.

src/chi/utilities/color.scss, src/website/views/utilities/color.pug
@mattnickles 
https://elasticbox.atlassian.net/browse/CHI-310
=> [CHI-310] Add -bg--grey-30 color utility

src/chi/components/textarea/_input-textarea.scss
@mattnickles 
https://elasticbox.atlassian.net/browse/CHI-311
=> [CHI-311] Increase line-height of -md textarea

src/chi/components/picker/_horizontal-picker-groups.scss, src/chi/components/picker/picker-groups.scss, src/chi/index.scss, src/website/views/components/picker-group.pug, test/chi/components/picker-group.pug
=> [CHI-290] Add Picker group component

src/chi/javascript/components/modal.js
This is using the same code @davidojedacl used for the Drawer component
=> [CHI-318] Disable body scroll when modal is open

src/chi/components/header/header.scss
=> Remove icon arrow svg in header inverse dropdown trigger

src/chi/utilities/sizing.scss, src/website/views/utilities/sizing.pug
=> [CHI-332] Add 720px max width to sizing utility

src/chi/components/steps/steps.scss
=> [CHI-339] Change step component base disabled color

src/chi/utilities/shadow.scss
=> [CHI-330] Add important to shadow utility values

src/chi/components/header/header.scss
=> [CHI-322] Title in base header component is missing color

src/chi/components/modal/modal.scss
=> [CHI-331] Replace modal back svg icon with chi web font icon

src/chi/components/steps/steps.scss, src/website/views/components/steps.pug
=> [CHI-333] Step components arent reseting default browser margin

src/chi/components/alert/_bubble.scss
=> [CHI - 344] Alert bubble icon center fix

cypress/integration/chi-custom-elements/number-input.spec.js
=> [CHI-349] Fix E2E Test Number Input bug

src/website/views/utilities/spacing.pug
=> [CHI-348] Fix misspelled class in spacing utility

src/chi/javascript/components/drawer.js
=> [CHI-329] Clicking drawer content should not close drawer component

src/chi/components/expansion-panel/expansion-panel.scss
=> [CHI-345] Fix long strings in expansion panel content

src/chi/components/dropdown/dropdown.scss, src/website/assets/scripts/chi-docs.js, src/website/layouts/partials/header.pug
=> [CHI-355] Add Ms Teams CHI channel link to support drop down

src/chi/utilities/color.scss, src/custom-elements/docs/docs.json, src/website/views/utilities/color.pug
=> [CHI-340] Add -bg--muted color utility

src/chi/components/drawer/drawer.scss
=> [CHI-326] Drawer component close icon should not scroll with content

src/chi/components/footer/footer.scss
=> [CHI-316] Footer component colums are not responsive

src/chi/components/sidebar/sidenav.scss, src/website/views/components/sidenav.pug
@mattnickles 
https://ctl.atlassian.net/browse/CHI-370
=> [CHI-370] Add Sidenav collapsed

src/chi/components/sidebar/sidenav.scss, src/website/views/components/sidenav.pug
Also group the examples in tabs for Initial and expanded states
@mattnickles
=> [CHi-379] Change sizes in Sidenav to -sm, -md and -lg

src/chi/components/sidebar/sidenav.scss, src/website/views/components/sidenav.pug
=> [CHI-360] Add inverse support to sidenav component

src/website/views/javascript/drawer.pug
@jllr @mattnickles @dani-cl-madrid 
https://ctl.atlassian.net/browse/CHI-375
=> [CHI-375] Drawer JavaScript documentation updated, added methods

src/website/assets/scripts/chi-docs.js, src/website/assets/scripts/globalConfigs.js, src/website/assets/styles/_docs-container.scss, src/website/layouts/default.pug, src/website/layouts/partials/header.pug, tasks/build-website-scripts.js
@dani-cl-madrid @SergioQCL @jllr @mattnickles 
https://ctl.atlassian.net/browse/CHI-346
=> [CHI-346] Added newer version availability check + made version dropdown dynamic

src/website/assets/scripts/chi-docs.js, src/website/assets/scripts/chiVersionCheck.js, src/website/assets/styles/_docs-container.scss, src/website/layouts/default.pug, src/website/layouts/partials/header.pug
@jllr @mattnickles @dani-cl-madrid @SergioQCL 
https://ctl.atlassian.net/browse/CHI-381
=> [CHI-381] Improved behaviour of new version alert banner of header

src/chi/components/steps/steps.scss, src/website/views/components/steps.pug
=> Chi 305 improve responsive behavior of step component

cypress/integration/chi-custom-elements/number-input.spec.js, src/custom-elements/docs/docs.json, src/custom-elements/src/components/number-input/number-input.tsx, src/website/views/custom-elements/number-input.pug
@jllr @dani-cl-madrid @SergioQCL @mattnickles 
https://ctl.atlassian.net/browse/CHI-365
=> [CHI-365] CE Number input with step

src/chi/foundations/typography/typography.scss, src/custom-elements/docs/docs.json, src/website/views/utilities/text.pug
=> [CHI-321] Add responsive classes text size line height text alignment

src/custom-elements/src/components/popover/popover.tsx
=> CHI-388 Improved Popover several reference found error message

src/custom-elements/docs/docs.json, src/custom-elements/src/components/badge/badge.tsx, src/website/views/custom-elements/badge.pug
@mattnickles 
https://ctl.atlassian.net/browse/CHI-392
=> [CHI-392] Fix misspellings in Badge CE

src/chi/components/input-wrapper.scss
https://ctl.atlassian.net/browse/CHI-400
=> [CHI-400] Fix input wrapper lint warnings

src/chi/components/tabs/tabs.scss, src/website/views/custom-elements/forms/toggle-switch.pug
- Fixed tabs component dropdown arrow position for -lg tabs
- Fixed toggle switch CE view issue
@jllr
=> [CHI-396] Fixed tabs component dropdown position in -lg

src/website/assets/styles/_docs-container.scss, src/website/assets/styles/_docs-header.scss, src/website/layouts/default.pug, src/website/layouts/partials/aside.pug, src/website/layouts/partials/header.pug
@janibolkvadze 
https://ctl.atlassian.net/browse/CHI-395
=> [CHI-395] Improve doc sidenav

src/custom-elements/src/components/alert/alert.tsx
=> Improved Alert CE title update lsitener

src/custom-elements/docs/docs.json, src/custom-elements/src/components/button/button.tsx, src/custom-elements/src/components/drawer/drawer.tsx, src/website/layouts/partials/header.pug, src/website/views/components/alert.pug, src/website/views/components/button.pug, src/website/views/components/drawer.pug, src/website/views/components/header.pug, src/website/views/components/modal.pug, src/website/views/components/sidenav.pug, src/website/views/javascript/drawer.pug, src/website/views/javascript/modal.pug, src/website/views/javascript/sidenav.pug, test/chi/components/alert-banner.pug, test/chi/components/alert-bubble.pug, test/chi/components/alert-toast.pug, test/chi/components/buttons.pug, test/chi/components/drawer.pug, test/chi/components/modals.pug
Added aria-label="Close" to:
- Button CE type="close"
- drawer CE close button
- Dismissible alert dismiss buttons
- Modals
- Sidenavs
- Alert, buttons, drawer, modal test cases
- Header close buttons
https://ctl.atlassian.net/browse/PE-3836
=> [CHI-3836] Fixed close button accessibility issue

src/website/assets/styles/_docs-container.scss, src/website/layouts/partials/aside.pug
Fixed redundant link accessibility issue of Chi documentation website
https://ctl.atlassian.net/browse/PE-3846
=> Fixed Redundant link accessibility issue

src/chi/components/checkbox/checkbox.scss, src/chi/components/radio/radio.scss, src/chi/components/toggle-switch/toggle-switch.scss, src/custom-elements/src/components/number-input/number-input.tsx, src/website/assets/styles/_docs-container.scss, src/website/views/components/button-group.pug, src/website/views/components/forms/number-input.pug, src/website/views/javascript/number-input.pug, test/chi/components/button-horizontal-groups.pug, test/chi/components/button-vertical-groups.pug, test/chi/components/input-number.pug
https://ctl.atlassian.net/browse/PE-3894
=> Added missing aria-labels to icon buttons

src/website/assets/scripts/chi-docs.js
Fixed h2 anchors of documentation website
=> [PE-3924] Fixed documentation h2 heading anchors

src/website/layouts/default.pug, src/website/views/getting-started/index.pug
Added support of defining unique description meta tags for docs pages
https://ctl.atlassian.net/browse/PE-3971
=> [PE-3971] Added meta description to docs to improve SEO rating

src/website/views/components/forms/range-slider.pug, src/website/views/components/forms/textarea.pug, src/website/views/components/popover.pug, src/website/views/javascript/date-picker.pug, src/website/views/javascript/drawer.pug, src/website/views/javascript/number-input.pug, src/website/views/javascript/range-slider.pug
Range slider
- Stored label and input in m-form__item
Textarea
- Added missing labels and stored in m-form__item
Popover
- Added missing a-label class
Datepicker
- Added missing labels and stored in m-form__item
Drawer
- Added aria-label to hamburger menu icon button
=> [PE-3918] Fixed code inconsistencies in documentation examples

src/website/layouts/partials/aside.pug, src/website/layouts/partials/header.pug, src/website/views/custom-elements/overview.pug, src/website/views/getting-started/browsers-devices.pug, src/website/views/getting-started/index.pug
Improved our Best Practices score by adding `rel="noopener"` to external links
=> [PE-3945] Added noopener to external links

src/website/layouts/partials/aside.pug
Fixed suspicious link accessibility error of 'Button' link
https://ctl.atlassian.net/browse/PE-3868
=> Fixed suspicious link accessibility error

src/website/views/components/table/_common.pug, src/website/views/components/table/index.pug
FYI:
For some reason, HTML-beautify-pug didn't work properly in the selectable table example, so I added the HTML code snippet manually
@jllr 
https://ctl.atlassian.net/browse/PE-3917
=> Fixed table empty label accessibility error

.sass-lint.yml, src/chi/components/activity/activity.scss, src/chi/components/alert/alert.scss, src/chi/components/buttons/_horizontal-button-groups.scss, src/chi/components/buttons/_vertical-button-groups.scss, src/chi/components/buttons/button-groups.scss, src/chi/components/icons/webfont-icons.scss, src/chi/components/input-number/_input-wrapper.scss, src/chi/components/input-number/input-number.scss, src/chi/components/input-text/_input-floating-label.scss, src/chi/components/input-text/_input.scss, src/chi/components/input-text/_label.scss, src/chi/components/input-text/input-text.scss, src/chi/components/navigation/navigation.scss, src/chi/components/picker/picker-groups.scss, src/chi/components/popover/popover.scss, src/chi/components/textarea/textarea.scss, src/chi/foundations/typography/root-typography.scss
- Fixed leading underscore SASS lint warning
- Fixed import statements in several components
- Increased max line SASS lint rule
- Fixed some linting errors
https://ctl.atlassian.net/browse/PE-4029
=> [PE-4029] Fixed leading-underscore SASS lint warning

src/website/assets/scripts/chiVersionCheck.js, src/website/layouts/partials/header.pug
- Prevented chaching of versions.json data
- Improved comparing method of current and production versions
@dani-cl-madrid @SergioQCL @mattnickles @jllr
=> [PE-3919] Fixed version check caching issue

src/custom-elements/docs/docs.json, src/custom-elements/stencil.config.ts
Fixed removing of `title=''` attribute of alert and popover CEs
@mattnickles @dani-cl-madrid @jllr 
https://ctl.atlassian.net/browse/PE-4071
=> [PE-4071] Fixed removing of title attribute

src/chi/javascript/components/auxiliary/overflow-menu.js, src/chi/javascript/components/navigation.js, src/website/views/javascript/sidenav.pug, src/website/views/javascript/tabs.pug
https://ctl.atlassian.net/browse/PE-3948
=> [PE-3948] Fixed same page link warnings in sidenav and tab component

src/chi/components/sidebar/sidenav.scss, src/chi/javascript/components/sidenav.js, src/chi/javascript/core/component.js, src/website/views/javascript/sidenav.pug
The first implementation of Enterprise Global Navigation 3rd level tabs.
Thoughts about the approach, class namings, etc? @mattnickles @jllr @dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4174
=> [PE-4174] Added Enterprise Global Navigation example to Sidenav component

src/website/views/components/button-group.pug
Fixed Button Group component Sizes example tabs
https://ctl.atlassian.net/browse/PE-4251
=> [PE-4251] Fixed Button group sizes example tabs

src/website/views/custom-elements/date-picker.pug
https://ctl.atlassian.net/browse/PE-4263
=> [PE-4263] Fixed Date Picker CE page accessibility

CHANGELOG.md, src/chi/components/header/header.scss, src/chi/utilities/color.scss, src/custom-elements/docs/docs.json, src/website/views/components/card.pug, src/website/views/components/header.pug, src/website/views/getting-started/whats-new.pug, src/website/views/utilities/color.pug, test/chi/components/header.pug
- Updated changelog.
- Simplified class names for enterprise header with horizontal navbar.
- Fixed bug in enterprise header with navbar component which broke the rendering of the divider if an inverse divider was used instead of a colorbar divider. This method should allow more flexibility.
- Added background-color utility for CenturyLink Teal color swatch.
- Removed random 'a' character in card component example code.
=> [PE-4275] Updated changelog and improvements for 1.4.0 release

tasks/watch.js
@mattnickles @jllr @dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4302
=> [PE-4302] Add Gulp watch for website layouts

src/custom-elements/docs/docs.json, src/custom-elements/package.json, src/custom-elements/src/components/badge/badge.tsx, src/custom-elements/src/components/button/button.tsx
@mattnickles @jllr @dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4366
=> [PE-4366] Updated Stencil to 1.8.9

src/custom-elements/src/components/number-input/number-input.tsx, src/website/views/custom-elements/number-input.pug
- Added support of `<chi-label>` to Number Input CE
- Updated Number Input CE page examples and code snippets accordingly
https://ctl.atlassian.net/browse/PE-4438
=> [PE-4438] Added chi-label for number input CE

src/chi/components/drawer/drawer.scss, src/custom-elements/docs/docs.json, src/custom-elements/src/components/drawer/drawer.tsx
Fixed Drawer CE header title heading level accessibilty issue
https://ctl.atlassian.net/browse/PE-4453
=> [PE-4453] Fixed Drawer CE accessibility issue

src/website/views/components/button/_examples.pug
https://ctl.atlassian.net/browse/PE-4455
=> [PE-4455] Removed Button tags docu example

package.json, src/custom-elements/docs/docs.json, tasks/build-website-views.js
https://ctl.atlassian.net/browse/PE-4502
=> [PE-4502] Fixed gulp build-website page exclusion

src/website/views/components/tooltip/_accessibility.pug, src/website/views/components/tooltip/_examples.pug, src/website/views/components/tooltip/_properties.pug, src/website/views/components/tooltip/index.pug
https://ctl.atlassian.net/browse/PE-4457
=> [PE-4557] Added Tooltip component page

src/custom-elements/src/components/alert/alert.tsx
Improved Alert title Mutation Observer management in connectedCallback and disconnectedCallback
@dani-cl-madrid @mattnickles @jllr 
https://ctl.atlassian.net/browse/PE-4520
=> [PE-4250] Improved Alert CE Mutation observer

src/custom-elements/src/components/popover/popover.tsx
Improved Popover title Mutation Observer management in connectedCallback and disconnectedCallback
@dani-cl-madrid @mattnickles @jllr 
https://ctl.atlassian.net/browse/PE-4521
=> [PE4521] Improved Popover CE Mutation observer

src/website/views/getting-started/browsers-devices.pug, src/website/views/getting-started/development-workflow.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/PE-4532
=> [PE-4532] Added development workflow page

src/website/views/components/price/_examples.pug
https://ctl.atlassian.net/browse/PE-4535
=> [PE-4535] Fixed Price page sizes example

src/website/views/components/forms/text-input/_examples.pug
https://ctl.atlassian.net/browse/PE-4533
=> [PE-4533] Fixed Text Input floating label example

cypress/integration/chi-custom-elements/expansion-panel.spec.js, src/custom-elements/docs/docs.json, src/custom-elements/src/components/expansion-panel/expansion-panel.tsx, src/custom-elements/stencil.config.ts, src/website/views/components/expansion-panel/_examples.pug, test/chi/custom-elements/expansion-panel.pug
@dani-cl-madrid @mattnickles @jllr 
https://ctl.atlassian.net/browse/PE-4477
=> [PE-4477] Added title attribute to Expansion panel

src/website/views/components/forms/select/_examples.pug
https://ctl.atlassian.net/browse/PE-4559
=> [PE-4559] Added Floating label Select example

cypress/integration/chi-js/enterprise-global-nav.spec.js, src/chi/javascript/components/sidenav.js, test/chi/js/enterprise-global-nav.pug
Added Cypress test for Enterprise Global Nav example of Sidenav.js
@dani-cl-madrid @jllr @mattnickles 
https://ctl.atlassian.net/browse/PE-4404
=> [PE-4404] Added Cypress test of Enterprise Global Nav

src/chi/components/picker/_horizontal-picker-groups.scss, src/chi/components/picker/picker-groups.scss, src/chi/components/picker/picker.scss, src/website/views/components/picker-group/_examples.pug, src/website/views/components/picker/_examples.pug, test/chi/components/picker-group.pug, test/chi/components/picker.pug
m-pickerGroup -> chi-picker-group
m-picker -> chi-picker__item
a-picker -> chi-picker
=> [PE-4581] Improve picker component

src/chi/index.scss, src/chi/skeletons/_shine.scss, src/chi/skeletons/alert.scss, src/chi/skeletons/badge.scss
https://ctl.atlassian.net/browse/PE-4607
=> [PE-4607] Added support of Badge CE skeleton

src/chi/index.scss, src/chi/skeletons/brand.scss
https://ctl.atlassian.net/browse/PE-4608
=> [PE-4608] Added support of Brand CE skeleton

src/chi/index.scss, src/chi/skeletons/_shine.scss, src/chi/skeletons/date-picker.scss
https://ctl.atlassian.net/browse/PE-4609
=> [PE-4609] Added support of Date Picker CE skeleton

cypress/integration/chi-custom-elements/number-input.spec.js, src/chi/components/input-number/_input-wrapper.scss, src/chi/components/input-number/_input.scss, src/chi/javascript/components/number-input.js, src/custom-elements/src/components/number-input/number-input.tsx, src/website/views/components/forms/number-input/_examples.pug, src/website/views/components/forms/number-input/_properties.pug, test/chi/components/input-number.pug
https://ctl.atlassian.net/browse/PE-4564
=> [PE-4564] Improve number input markup

src/chi/components/input-text/_input-wrapper.scss, src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx
https://ctl.atlassian.net/browse/PE-4700
=> [PE-4700] Improved Date Picker web component icon rendering

src/chi/javascript/components/sidenav.js
@dani-cl-madrid 
https://ctl.atlassian.net/browse/PE-4732
=> [PE-4732] Fixed Sidenav IE11 compatibility

src/website/views/components/drawer/_examples.pug, src/website/views/components/expansion-panel/_examples.pug, src/website/views/components/popover/_examples.pug
https://ctl.atlassian.net/browse/PE-4735
=> [PE-4735] Changed button to chi-button in Web Component examples

src/chi/components/date-picker/date-picker.scss, src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx
https://ctl.atlassian.net/browse/PE-4738
=> [PE-4738] Fixed Date Picker whitespace bug

src/custom-elements/docs/docs.json, src/custom-elements/src/components/drawer/drawer.tsx, src/custom-elements/stencil.config.ts, src/website/views/components/drawer/_examples.pug, test/chi/custom-elements/drawer.pug
https://ctl.atlassian.net/browse/PE-4739
=> [PE-4739] Change drawer headless to no-header

src/website/assets/styles/chi-docs.scss, src/website/views/getting-started/whats-new.pug
- Added guides of automated classname replacement scripts
Thoughts about adding guides regarding removed legacy code?
Also, we need to communicate markup changes of number input component
@mattnickles @jllr
https://ctl.atlassian.net/browse/PE-4641
=> [PE-4641] Added classname replacement guide

src/website/assets/scripts/chi-docs.js
https://ctl.atlassian.net/browse/PE-4791
=> [PE-4791] Fixed chi-docs hashUrl targetting tabs bug

src/website/views/components/forms/number-input/_examples.pug
https://ctl.atlassian.net/browse/PE-4792
=> [PE-4792] Fixed chi-number-input accessibility errors

src/chi/components/date-picker/date-picker.scss, src/custom-elements/src/components/date-picker/date-picker.tsx
https://ctl.atlassian.net/browse/PE-4800
=> [PE-4800] Fixed IE11 Date Picker icon positioning

src/custom-elements/src/components/progress/progress.tsx
https://ctl.atlassian.net/browse/PE-4807
=> [PE-4807] Fixed IE11 Progress web component value atrr

src/website/assets/scripts/chi-docs.js, src/website/assets/scripts/chiVersionCheck.js, src/website/layouts/partials/header.pug
https://ctl.atlassian.net/browse/PE-4798
=> [PE-4798] Fixed IE11 Invalid character bug

src/custom-elements/src/components/number-input/number-input.tsx, src/website/views/components/forms/number-input/_examples.pug
https://ctl.atlassian.net/browse/PE-4811
=> [PE-4811] Fixed number input CE re-rendering

src/website/views/components/forms/number-input/_examples.pug
https://ctl.atlassian.net/browse/PE-4443
=> [PE-4443] Added Labels to Number Input HTML Blueprints

src/chi/components/date-picker/date-picker.scss, src/custom-elements/src/components/date-picker/date-picker.tsx
https://ctl.atlassian.net/browse/PE-4927
=> [PE-4927] Fixed Date Picker WC -disabled

src/website/assets/scripts/chi-docs.js
https://ctl.atlassian.net/browse/PE-4932
=> [PE-4932] Improved hash target validation to chi-docs

src/website/views/components/drawer/_examples.pug, src/website/views/components/drawer/_properties.pug
https://ctl.atlassian.net/browse/PE-4938
Added functional examples for Web components and Html Blueprint code snippets in Drawer component page.
=> [PE-4938] Improved drawer doc examples

Dockerfile
@janibolkvadze @jllr 
https://ctl.atlassian.net/browse/PE-5012
=> [PE-5102] Updated docker configuration

src/website/layouts/partials/header.pug
https://ctl.atlassian.net/browse/PE-5120
=> [PE-5120] Fixed Chi version variable typo in header.pug

tasks/build-chi-scripts.js
https://ctl.atlassian.net/browse/FSPE-5250
=> [FSPE-5250] Improved chi.js global variable declaration

src/chi/components/pagination/pagination.scss, src/chi/components/tables/tables.scss, src/website/views/components/forms/text-input/_examples.pug, src/website/views/components/forms/textarea/_examples.pug, src/website/views/components/pagination/_examples.pug
https://ctl.atlassian.net/browse/FSPE-5256
=> [FSPE-5256] Fixed documentation defects

src/chi/_variables.scss, src/chi/components/tooltip/tooltip.scss, src/chi/javascript/components/tooltip.js, src/website/views/components/tooltip/_examples.pug, src/website/views/components/tooltip/index.pug
* Changed: Tooltip styles to look less like inverse drop down menus.
* Added: Sass font-weight variables.
* Fixed: Typo in Tooltip code example.
=> [FSPE-5284] Improve tooltip styles

src/website/views/components/badge/_examples.pug, src/website/views/components/button/_examples.pug, src/website/views/components/card/_examples.pug, src/website/views/getting-started/development-workflow.pug
Hey @jllr, @janibolkvadze, @mattnickles, could you please review? 
I tried to add some terms in bold, although I haven't seen you really using it across the doc. I've used #[] for it, but not sure if that will work in our case.
=> [FSPE-5271] Solid vs Base and some other minor fixes

CHANGELOG.md, package.json, src/chi/_variables.scss, src/chi/utilities/border.scss, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug, src/website/views/utilities/border.pug
- Border utility now supports the color transparent to hide an elements border without altering its size. Requirement for portal.
- Border utility documentation now includes usage guidelines for each example.
- Added variables for Border utility colors.
=> [FSPE-5176] Improved border utility colors

src/chi/javascript/components/tooltip.js
https://ctl.atlassian.net/browse/FSPE-5294
@dani-cl-madrid @SergioQCL @mattnickles @jllr
=> [FSPE-5294] Added 0.5s delay to Tooltip animation

src/chi/components/tooltip/tooltip.scss, src/chi/javascript/components/tooltip.js, src/custom-elements/docs/docs.json, src/website/views/components/tooltip/_examples.pug
@dani-cl-madrid @SergioQCL @mattnickles @jllr 
https://ctl.atlassian.net/browse/FSPE-5316
=> [FSPE-5316] Added support of Light Tooltip

src/chi/components/popover/popover.scss, src/custom-elements/docs/docs.json
https://ctl.atlassian.net/browse/FSPE-5245
@mattnickles @jllr
=> [FSPE-5245] Fixed Popover arrow positioning

src/custom-elements/src/components/drawer/drawer.tsx
@dani-cl-madrid @SergioQCL @mattnickles @jllr 
https://ctl.atlassian.net/browse/FSPE-5309
=> [FSPE-5309] Fixed Drawer X button close behavior

src/website/views/components/dropdown/_examples.pug
=> Fix item 3 text that was not the same and not even truncated

src/chi/components/steps/steps.scss
https://ctl.atlassian.net/browse/FSPE-5409
=> [FSPE-5409] Fixed misalignment in -active base steps component in IE11

src/website/views/components/header/_examples.pug
https://ctl.atlassian.net/browse/FSPE-5411
=> [FSPE-5411] Updated html blueprint in Portal header, Impersonation bar and Header w/ title and buttons examples

src/chi/javascript/components/sidenav.js
https://ctl.atlassian.net/browse/FSPE-5444
@dani-cl-madrid @SergioQCL
=> [FSPE-5444] Added hover behavior of Sidenav single level items

src/website/views/components/drawer/_examples.pug
https://ctl.atlassian.net/browse/FSPE-5322
=> [FSPE-5322] Improved documentation for drawer close buttons

src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx, src/custom-elements/src/components/date/date.tsx
@dani-cl-madrid 
https://ctl.atlassian.net/browse/FSPE-5569
=> [FSPE-5569] Fixed dayjs locale type definition

src/chi/javascript/components/drawer.js, src/chi/javascript/components/sidenav.js
https://ctl.atlassian.net/browse/FSPE-5551
=> [FSPE-5551] Improved dispose of Sidenav and Drawer components

CHANGELOG.md, src/website/views/getting-started/whats-new.pug
=> Updated chi release with Mobile navigation component

src/custom-elements/src/components/pagination/pagination.tsx
@dani-cl-madrid @SergioQCL @jllr
https://ctl.atlassian.net/browse/FSPE-5664
=> [FSPE-5664] Fixed chiPageChange event of Pagination

src/chi/javascript/components/drawer.js, src/chi/javascript/components/sidenav.js
=> Removed disposing of Drawers associated with Sidenav

CHANGELOG.md, package.json, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
=> Prepare chi release 2.5.1

CHANGELOG.md, package.json, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
=> [FSPE-5767] Prepare Chi 2.6.0 release

src/chi/javascript/components/sidenav.js
https://ctl.atlassian.net/browse/FSPE-5833
=> [FSPE-5833] Improved single level menu item validation of Sidenav

src/custom-elements/docs/docs.json, src/custom-elements/src/components/popover/popover.tsx
https://ctl.atlassian.net/browse/FSPE-6024
=> [FSPE-6024] Fixed Popover WC shown/hidden event emission

src/chi/components/picker/picker-groups.scss
https://ctl.atlassian.net/browse/FSPE-6029
=> [FSPE-6029] Fixed text wrapping bug in picker group

CHANGELOG.md, package.json, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6028
=> [FSPE-6028] Prepare release for version 3.1.0

src/chi/components/stat/stat.scss, src/website/views/templates/portal.pug
https://ctl.atlassian.net/browse/FSPE-6120
=> [FSPE-6120] Added min-height to portal stat component

src/website/views/components/modal/_properties.pug
https://ctl.atlassian.net/browse/FSPE-5010
=> [FSPE-5010] Documented Chi Modal methods

src/website/views/components/dropdown/_properties.pug
https://ctl.atlassian.net/browse/FSPE-6268
=> [FSPE-6268] Documented Dropdown Chi JS methods

cypress/integration/chi-js/enterprise-global-nav.spec.js
https://ctl.atlassian.net/browse/FSPE-6270
=> [FSPE-6270] Fixed Enterprise Nav Cypress test

CHANGELOG.md, package.json, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6294
=> [FSPE-6294] Prepared 3.1.1 release

src/chi/components/toggle-switch/toggle-switch.scss
https://ctl.atlassian.net/browse/FSPE-6117
=> [FSPE-6117] Removed toggle switch margin when label is present

src/chi/index.scss, src/chi/utilities/vertical-align.scss, src/website/assets/styles/_docs-container.scss, src/website/views/utilities/vertical-align.pug
https://ctl.atlassian.net/browse/FSPE-6371
=> [FSPE-6371] Added vertical-align utility

src/chi/components/input-wrapper.scss, src/custom-elements/src/components/number-input/number-input.scss, src/custom-elements/src/components/toggle-switch/toggle-switch.scss
https://ctl.atlassian.net/browse/FSPE-6337
=> [FSPE-6337] Fixed vertical alignment of inline web components

cypress/integration/chi-js/sidenav.spec.js, test/chi/js/sidenav.pug
Improved E2E test for Chi Sidenav component functionality
@janibolkvadze , could you please review the PR
=> [FSPE-6065] Improve E2E test for Chi Sidenav component functionality

CHANGELOG.md, package.json, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6377
=> [FSPE-6377] Prepared Chi 3.2.0 release

cypress/integration/chi-js/popover.spec.js, test/chi/js/popover.pug
Create E2E test for Chi Popover component functionality
=> [FSPE-6061] Created E2E test for Chi Popover component functionality

cypress/integration/chi-js/modal.spec.js, test/chi/js/modal.pug
Written E2E test cases for Chi Modal Component functionality
@janibolkvadze Could you please review
=> [FSPE-6060] E2E Test for Chi modal component functionality

src/website/views/components/modal/_examples.pug, src/website/views/templates/portal.pug
https://ctl.atlassian.net/browse/FSPE-6372
=> [FSPE-6372] Added docs example for portal error modal

src/custom-elements/docs/docs.json, src/custom-elements/src/components/progress/progress.tsx, src/website/views/components/progress/_examples.pug, src/website/views/components/progress/_properties.pug
https://ctl.atlassian.net/browse/FSPE-4807
=> [FSPE-4807] Fixed Progress Web Component IE11 rendering issue

CHANGELOG.md, src/website/views/components/accordion/index.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6453
=> [FSPE-6453] Prepared release for Chi v3.3.0

cypress/integration/chi-js/chi-drawer.spec.js, test/chi/js/chi-drawer.pug
=> [FSPE-6062] E2E test for Chi Drawer component functionality

src/chi/javascript/components/modal.js, src/website/views/components/modal/_properties.pug
https://ctl.atlassian.net/browse/FSPE-6505
=> [FSPE-6505] Added support of event emission to Modal JS

cypress/integration/chi-js/accordion.spec.js, test/chi/js/accordion.pug
Added e2e test for chi accordion component
@SwathiLingareddy / @janibolkvadze  could you please review
=> [FSPE-6494] - Added e2e test for chi accordion component

src/chi/components/picker/_horizontal-picker-groups.scss, src/chi/components/picker/picker.scss, src/custom-elements/docs/docs.json, src/website/views/components/picker-group/_examples.pug, src/website/views/components/picker/_examples.pug
https://ctl.atlassian.net/browse/FSPE-6502
=> [FSPE-6502] Added disabled support to picker and picker group

src/website/views/components/header/_examples.pug
Added tooltip to chi header component example 
@janibolkvadze  could you please review
=> [FSPE-6495] Added tooltips to header component documentation examples

src/chi/javascript/components/tooltip.js
https://ctl.atlassian.net/browse/FSPE-6580
=> [FSPE-6580] Removed Tooltip position animation

src/chi/components/alert/_alert-common.scss, src/chi/components/backdrop/backdrop.scss, src/chi/components/badge/badge.scss, src/chi/components/breadcrumb/breadcrumb.scss, src/chi/components/drawer/drawer.scss, src/chi/components/expansion-panel/expansion-panel.scss, src/chi/components/footer/footer.scss, src/chi/components/grid/grid.scss, src/chi/components/header/header.scss, src/chi/components/html-select/html-select.scss, src/chi/components/icons/webfont-icons.scss, src/chi/components/input-file/input-file.scss, src/chi/components/input-number/_input-wrapper.scss, src/chi/components/input-text/_input-floating-label.scss, src/chi/components/input-text/_input.scss, src/chi/components/mobile-navigation/mobile-navigation.scss, src/chi/components/pagination/pagination.scss, src/chi/components/picker/picker.scss, src/chi/components/range-slider/range-slider.scss, src/chi/components/sidebar/sidenav.scss, src/chi/components/tabs/tabs.scss, src/chi/components/toggle-switch/toggle-switch.scss, src/chi/components/tooltip/tooltip.scss, src/chi/skeletons/button.scss
https://ctl.atlassian.net/browse/FSPE-6579
=> [FSPE-6579] Resolved sass lint warnings

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/chiVersionCheck.js, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/components/forms/number-input/_examples.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6596
=> [FSPE-6596] Prepared Chi 3.4.0 release

src/website/views/components/accordion/_examples.pug, src/website/views/components/data-table/_examples.pug, src/website/views/components/forms/checkbox/_examples.pug
https://ctl.atlassian.net/browse/FSPE-6598
=> [FSPE-6598] Changed duplicate IDs and fixed odd behavior in accordion tabs

src/custom-elements/docs/docs.json, src/custom-elements/src/components/button/button.tsx, src/website/views/components/popover/_examples.pug
[FSPE-6621] Added Popover open  on hover example
[FSPE-6621]: https://ctl.atlassian.net/browse/FSPE-6621
=> [FSPE-6621] Added Popover open  on hover example

src/chi-vue/package.json, src/chi-vue/src/App.vue, src/chi-vue/src/components/tooltip/tooltip.tsx, src/chi-vue/src/constants/classes.ts, src/chi-vue/src/constants/constants.ts, src/chi-vue/src/constants/events.ts, src/chi-vue/src/constants/types.ts, src/chi-vue/src/views/TooltipView.vue
@dani-cl-madrid @SergioQCL @aryaroudi
https://ctl.atlassian.net/browse/FSPE-6584
=> [FSPE-6584] Implemented Tooltip component in Chi Vue

src/chi/utilities/flex.scss, src/website/views/utilities/flex.pug
https://ctl.atlassian.net/browse/FSPE-6599
=> [FSPE-6599] Added flex-basis to Flex utilities

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6692
=> [FSPE-6692] Prepare release for 3.5.0

src/chi/components/accordion/accordion.scss
https://ctl.atlassian.net/browse/FSPE-6711
=> [FSPE-6711] Changed nested portal accordion styles

src/chi/components/picker/_horizontal-picker-groups.scss, src/website/views/templates/portal.pug
https://ctl.atlassian.net/browse/FSPE-6712
=> [FSPE-6712] Changed portal picker group hover styles

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-6799
=> [FSPE-6799] Prepared 3.6.0 release

src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx, src/custom-elements/src/components/date/date.tsx
Here is an example of `resetDate()` functionality https://codepen.io/janibolkvadze/pen/RwGZzOB
https://ctl.atlassian.net/browse/FSPE-6800
@dani-cl-madrid
=> [FSPE-6800] Added support of resetDate to Date Picker wc

CHANGELOG.md, src/chi/components/date-picker/date-picker.scss, src/chi/components/time-picker/time-picker.scss, src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx, src/custom-elements/src/components/time-picker/time-picker.tsx, src/custom-elements/src/components/time/time.tsx, src/custom-elements/src/constants/classes.ts, src/custom-elements/src/constants/constants.ts, src/website/views/components/date-picker/_examples.pug, src/website/views/components/time-picker/_examples.pug, src/website/views/components/time-picker/_properties.pug, src/website/views/getting-started/whats-new.pug
@dani-cl-madrid @SergioQCL
https://ctl.atlassian.net/browse/FSPE-3448
=> [FSPE-3448] implement Chi time & Chi Time Picker web components

src/website/views/foundations/accessibility/other.pug, src/website/views/foundations/accessibility/overview.pug, src/website/views/foundations/accessibility/page-structure.pug, src/website/views/foundations/accessibility/text.pug, src/website/views/foundations/accessibility/using-keyboard.pug, src/website/views/getting-started/index.pug
https://ctl.atlassian.net/browse/FSPE-6885
=> [FSPE-6885] Fixed accessibility typos

src/chi/components/data-table/data-table.scss, src/website/views/components/data-table/_examples.pug
https://ctl.atlassian.net/browse/FSPE-6923
=> [FSPE-6923] Created 3rd level hierarchy in data table

src/website/views/components/tooltip/_examples.pug
https://ctl.atlassian.net/browse/FSPE-6757
=> [FSPE-6757] Added Disabled button Tooltip example

src/chi/components/time-picker/time-picker.scss, src/custom-elements/src/components/time-picker/time-picker.tsx, src/custom-elements/src/components/time/time.tsx, src/custom-elements/src/constants/classes.ts, src/custom-elements/src/constants/constants.ts
https://ctl.atlassian.net/browse/FSPE-6833
=> [FSPE-6833] Added Time Picker second iteration features

src/custom-elements/docs/docs.json, src/custom-elements/src/components/date-picker/date-picker.tsx, src/custom-elements/src/components/date/date.tsx, src/custom-elements/src/constants/constants.ts
@SergioQCL 
https://ctl.atlassian.net/browse/FSPE-6973
=> [FSPE-6973] Added support of language change to Date wc

src/chi/javascript/components/tab.js, src/chi/javascript/core/chi.js, src/website/views/components/tabs/_examples.pug
https://ctl.atlassian.net/browse/FSPE-4663
@dani-cl-madrid @SergioQCL @mattnickles @jllr 
https://ctl.atlassian.net/browse/FSPE-4663
=> [FSPE-4663] Added support of keyboard control to Tabs

src/chi/_variables.scss, src/chi/foundations/fonts/fonts.scss, src/chi/foundations/typography/typography.scss, src/website/views/utilities/text.pug
https://ctl.atlassian.net/browse/FSPE-6990
=> [FSPE-6990] Added support for bolder font weight

src/chi/components/data-table/data-table.scss, src/website/views/components/data-table/_examples.pug
https://ctl.atlassian.net/browse/FSPE-6972
=> [FSPE-6972] Improved striped behavior and added row child container for special cases in data table

package.json, src/chi/index.scss, src/chi/utilities/focus-visibility.scss, tasks/build-chi-scripts.js
@SergioQCL @mattnickles @jllr 
https://ctl.atlassian.net/browse/FSPE-5297
=> [FSPE-5297] Added support of Focus Visibility management to Chi.js

src/website/views/components/spinner/_examples.pug
https://ctl.atlassian.net/browse/FSPE-7011
=> [FSPE-7011] Fixed unnecessary tag in spinner docs

src/chi/components/tables/tables.scss, src/chi/index.scss, src/chi/utilities/overflow.scss, src/custom-elements/docs/docs.json, src/website/views/components/brand/_examples.pug, src/website/views/components/drawer/_examples.pug, src/website/views/components/mobile-navigation/_examples.pug, src/website/views/components/sidenav/_examples.pug, src/website/views/templates/portal.pug, src/website/views/utilities/overflow.pug, test/chi/components/brand.pug, test/chi/components/price.pug, test/chi/custom-elements/brand.pug
https://ctl.atlassian.net/browse/FSPE-6998
=> [FSPE-6998] Added overflow utility

src/chi/components/card/card.scss, src/chi/components/expansion-panel/expansion-panel.scss, src/chi/components/modal/modal.scss
https://ctl.atlassian.net/browse/FSPE-6015
=> [FSPE-6015] Fixed margin on adjacent sibling web component buttons

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-7065
=> [FSPE-7065] Prepared 3.8.0 release

src/chi/components/mobile-navigation/mobile-navigation.scss, src/chi/javascript/components/mobile-navigation.js
@cristb
https://ctl.atlassian.net/browse/FSPE-7214
=> [FSPE-7214] Improved MobileNav drawer target validation

scripts/entrypoint.sh, src/chi-vue/.npmrc, src/chi-vue/package.json
https://ctl.atlassian.net/browse/FSPE-7218
=> [FSPE-7218] Added support of chi publish-chi-vue

src/chi/index.scss, src/chi/utilities/image.scss, src/website/views/utilities/image.pug
https://ctl.atlassian.net/browse/FSPE-7170
=> [FSPE-7170] Added responsive image utility

src/chi/foundations/typography/typography.scss, src/custom-elements/docs/docs.json, src/custom-elements/src/constants/color.ts, src/website/views/components/icon/_examples.pug, src/website/views/utilities/color.pug, src/website/views/utilities/text.pug
https://ctl.atlassian.net/browse/FSPE-7166
=> [FSPE-7166] Added support for lumen orange to color utility

src/boilerplates/angular/chi-angular-boilerplate/src/app/header/header.component.html, src/boilerplates/es6/chi-vue-es6-boilerplate/src/components/Header.vue, src/boilerplates/react/chi-react-boilerplate/src/components/header.tsx, src/boilerplates/stencil/chi-stencil-boilerplate/src/components/app-header/app-header.tsx, src/boilerplates/vue/chi-vue-boilerplate/src/components/Header.vue, src/website/views/components/header/_examples.pug, test/chi/components/header.pug
https://ctl.atlassian.net/browse/FSPE-7309
=> [FSPE-7309] Added target blank to external links in header component

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/chi-vue/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/assets/styles/_docs-header.scss, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-7310
=> [FSPE-7310] Prepared 3.9.0 release

src/chi/components/header/header.scss
https://ctl.atlassian.net/browse/FSPE-7316
=> [FSPE-7316] Removed chi-search__input in collapsed search input css header.scss

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/chi-vue/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/components/link/_examples.pug, src/website/views/components/link/index.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-7344
=> [FSPE-7344] Prepared 3.10.0 release

src/chi/javascript/components/popover.js, src/custom-elements/src/components/popover/popover.tsx, src/website/views/components/stat/_examples.pug
Helpful information goes here.
=> [FSPE-7379] Changed Popover component positioning

CHANGELOG.md, package.json, src/boilerplates/angular/chi-angular-boilerplate/src/index.html, src/boilerplates/es6/chi-vue-es6-boilerplate/public/index.html, src/boilerplates/react/chi-react-boilerplate/public/index.html, src/boilerplates/stencil/chi-stencil-boilerplate/src/index.html, src/boilerplates/vue/chi-vue-boilerplate/public/index.html, src/chi-vue/public/index.html, src/custom-elements/src/index.html, src/website/assets/scripts/globalConfigs.js, src/website/layouts/partials/header.pug, src/website/layouts/partials/titlebar.pug, src/website/views/components/tooltip/_examples.pug, src/website/views/getting-started/installation.pug, src/website/views/getting-started/whats-new.pug
https://ctl.atlassian.net/browse/FSPE-7378
=> [FSPE-7378] Prepared release for 3.11.0

src/chi/javascript/components/sidenav.js
https://ctl.atlassian.net/browse/FSPE-7338
=> [FSPE-7338] Added delay to sidenav with openOnHover
